services:
  lux-id:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    extra_hosts:
      - "id.lux.network:host-gateway"
      - "172.17.0.1:host-gateway"
    depends_on:
      - db-lux-id
      - redis-lux-id
    environment:
      RUNNING_IN_DOCKER: "true"
    # volumes:
    #   - /etc/lux/compose/lux-id-prod-c0gkof/app.conf:/conf/app.conf
    tmpfs:
      - /tmp:exec,mode=1777
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.well-known.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.lux-id-csp.headers.customResponseHeaders.Content-Security-Policy=connect-src 'self' https://id.lux.network http://id.lux.network;"
      - "traefik.http.routers.lux-id-http.rule=Host(`id.lux.network`)"
      - "traefik.http.routers.lux-id-http.entrypoints=web"
      - "traefik.http.routers.lux-id-http.middlewares=well-known,lux-id-csp,redirect-to-https"
      - "traefik.http.routers.lux-id-https.rule=Host(`id.lux.network`)"
      - "traefik.http.routers.lux-id-https.entrypoints=websecure"
      - "traefik.http.routers.lux-id-https.middlewares=well-known,lux-id-csp"
      - "traefik.http.routers.lux-id-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.lux-id.loadbalancer.server.port=8000"
    networks:
      - lux-network
      - internal-network-lux-id
  db-lux-id:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - lux-id-mysql:/var/lib/mysql
    networks:
      - internal-network-lux-id

  redis-lux-id:
    restart: always
    image: redis:7-alpine
    volumes:
      - lux-id-redis:/data
    networks:
      - internal-network-lux-id

volumes:
  lux-id-mysql:
    name: lux-id-mysql-prod
  lux-id-redis:
    driver: local
networks:
  internal-network-lux-id:
  lux-network:
    external: true