services:
  lux-id:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
    networks:
      - lux-network
  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lux
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql
    networks:
      - lux-network

  redis:
    restart: always
    image: redis:7-alpine
    # volumes:
    #   - lux-id-dev-redis:/data
    networks:
      - lux-network

networks:
  lux-network:
    driver: bridge