import React from "react";
import {MetaMaskAvatar} from "react-metamask-avatar";

class AccountAvatar extends React.Component {
  render() {
    const {src, size, width, height} = this.props;
    // The avatar for Metamask account is directly generated by an algorithm based on the address
    // src = "metamask:0xC304b2cC0Be8E9ce10fF3Afd34820Ed306A23600";
    const matchMetaMask = src.match(/^metamask:(\w+)$/);
    if (matchMetaMask) {
      const address = matchMetaMask[1];
      return (
        <MetaMaskAvatar address={address} size={size} />
      );
    }
    if (size !== undefined) {
      return (
        <img width={size} height={size} src={src} />
      );
    } else if (width === undefined) {
      return (
        <img height={height} src={src} />
      );
    } else if (height === undefined) {
      return (
        <img width={width} src={src} />
      );
    }
  }
}

export default AccountAvatar;
